:source-highlighter: highlightjs
:numbered:

ifdef::env-github[]
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

= Aplicação Distribuída de Mensagens Instantâneas com Balanceador de Carga utilizando WebSocket com Node.js (link:https://kinolien.github.io/gitzip/?download=/manoelcampos/sd-websockets/tree/master/2.2-distributed-websocket[zip])

Esta é uma versão distribuída do chat com WebSockets e Node.js link:../2.1-websocket-chat-nodejs[apresentado anteriormente].
A aplicação possui um balanceador de carga que decide qual servidor vai atender o usuário. 

Você pode iniciar múltiplos servidores na mesma máquina, onde cada um vai executar em uma porta selecionada aleatoriamente. 
Ao iniciar cada servidor, ele conecta via WebSockets no balanceador de carga e informa seu endereço.
O balanceador então guarda a lista de endereços dos servidores ativos.
Quando um servidor é fechado, ele é removida da lista do balanceador.

Os usuários conectados em um mesmo servidor podem mandar mensagens em broadcast entre eles.
Se um usuário desejar mandar uma mensagem privada para um usuário de um mesmo ou outro servidor, pode digitar `login@endereco_servidor_destino:porta mensagem`. 
Neste caso, o balanceador de carga (que conhece o endereço de todos os servidores online) irá:

- verificar que a mensagem é privada;
- localizar o servidor de destino;
- e encaminhar a mensagem a ele. 

Tal servidor então procura o usuário de destino e entrega a mensagem.

== Informações Adicionais

Informações sobre instalação, estrutura, dependências e outras devem ser consultadas no link:../2.1-websocket-chat-nodejs[projeto anterior].

== Executando a Aplicação

=== Balanceador de Carga e Servidores

Podemos iniciar o balanceador de carga em http://localhost:8000 com o comando abaixo:

[source,bash]
----
node load-balancer.js
----

Depois, pode-se abrir quantos terminais desejar e em cada terminal iniciar uma instância diferente do servidor da aplicação com o comando: 

[source,bash]
----
npm start
----

Cada servidor vai iniciar em localhost numa porta escolhida aleatoriamente.
Como a aplicação deve ser acessada sempre pelo balanceador de carga, o usuário não precisa saber o endereço dos servidores.

=== Cliente

Para abrir a interface web da aplicação, basta acessar o endereço do balanceador de carga em http://localhost:8000
que ele vai direcionar a requisição para um servidor disponível.

== AVISO

Este é apenas um projeto de exemplo, mostrando que não é complexo implementar
um balanceador de carga e a comunicação entre diferentes servidores usando WebSockets.
Apesar disto, observe que é bastante trabalhoso implementar algo assim.

Esta implementação serve apenas para efeitos didáticos e posusi alguns problemas.
O balanceador de carga está fazendo mais do que deveria, ele: 

- redireciona cada cliente para um servidor existente;
- mas também é responsável por intermediar a troca de mensagens privadas entre clientes do mesmo servidor ou de servidores distintos.

Isto vai fazer com que o balanceador fique mais tempo ocupado, 
podendo prejudicar a agilidade no redirecionamento das conexões dos clientes, afetando a escalabilidade do sistema.
Em uma aplicação real, o ideal seria ter um servidor específico apenas para encaminhar as mensagens privadas.
No entanto, sendo este um projeto apenas de exemplo, e para não tornar a implementação mais extensa,
optou-se por incluir tal responsabilidade no balanceador. 

Se desejar ver uma aplicação mais realista que utiliza o https://redis.io[Redis] (um servidor de cache) para armazenar dados temporários compartilhados
entre as diversas aplicações em execução, acesse https://medium.com/containers-on-aws/scaling-a-realtime-chat-app-on-aws-using-socket-io-redis-and-aws-fargate-4ed63fb1b681[este link].
Um vídeo mostrando o desenvolvimento de tal aplicação está disponível link:https://youtu.be/IEvLkwdFgnU[aqui].
Há legendas em inglês, que você pode traduzir para o português no YouTube.